#@data/values
---
credentials:
- env_id: "255"
  env_instance: "01"
  env_password: "ENV-PASSWORD-GOES-HERE"   
- env_id: "255"
  env_instance: "02"
  env_password: "ENV-PASSWORD-GOES-HERE"
- env_id: "260"
  env_instance: "01"
  env_password: "ENV-PASSWORD-GOES-HERE"
 