apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: the-bosh-fundamentals
spec:
  portal:
    # index: https://www.example.com/
    catalog:
      visibility: public
    password: VMware
    registration:
      # type: anonymous
      type: one-step
      enabled: false
  workshops:
  - name: lab-tas-fundamentals
    capacity: 3
    reserved: 1
    expires: 1h
    orphaned: 5m
  - name: tas4ops-fundamentals
    capacity: 3
    reserved: 1
    expires: 1h
    orphaned: 5m
    