apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: the-bosh-fundamentals
spec:
  portal:
    registration:
      type: anonymous
    # index: https://www.example.com/
    catalog:
      visibility: public
    password: VMware
     #registration:
       #type: anonymous
       #type: one-step
       #enabled: false
  workshops:
  - name: tas4ops-fundamentals
    capacity: 10
    reserved: 1
    expires: 4h
    orphaned: 15m
    
